# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_name', models.CharField(max_length=30)),
                ('people_positive', models.IntegerField(default=0)),
                ('people_negative', models.IntegerField(default=0)),
            ],
        ),
    ]
